### ISSUE TITLE
Non-blocking Smart-ID polling requests

### ISSUE THREAD

**Issue by indreksiitan** [SK-EID/smart-id-php-client#2]
Is there a way to use Smart-ID in the same way as Mobile-ID, making polling calls from the frontend?

Mobile-ID works so that:
 * We make a first API call to initialize the authentication/signing, get back either an error (such as user does not have Mobile ID enabled) or the verification code + session ID
 * We then make polling calls via frontend every N seconds until we get back either a successful response or a final error

Currently, all examples like https://github.com/SK-EID/smart-id-php-client/wiki/Examples-of-using-it have implemented it so that the verification code is generated (and can then be shown to the user) and then a call is made to authenticate(), which ends up in SessionStatusPoller::pollForFinalSessionStatus(), which in turn implements a while loop until it gets back a success, error or a timeout.

This implementation has a dew drawbacks:
 * At the time of calculating and showing the verification code to the user we don't really know yet if the user has Smart-ID at all. So if we show that to user and then make a followup Ajax call to init the blocking authenticate() call, the user will falsely see a "Success, your verification code is 1234" message for a brief moment.
 * Since the request is sitting in a while loop, this will block the PHP default file-based session until completed, so in case the user will hit reload, the following request will wait for the session file until the authenticate() call times out.

The SessionStatusPoller has all the methods needed to implement a Mobile-ID like solution, but they are all either private or protected, so cannot be called from the client implementation.

Is this intentional?

**Comment by IndrekHaav** [comment]
A two-stage (start request, poll for status) process like Mobile-ID would indeed be great to have. As a workaround, it's possible to approximate it using existing public methods, although this produces a fair amount of duplicated code.

To start the authentication process, instead of creating and configuring an instance of `Client`, create instances of `SmartIdRestConnector` and `AuthenticationSessionRequest` (setting necessary properties on the latter), then call `$connector->authenticateWithIdentity($identity, $request)`. This will return an instance of `AuthenticationSessionResponse`, from which you can get the session ID that needs to be saved on the server (together with the authentication hash).

To check authentication status, create instances of `SmartIdRestConnector` and `SessionStatusPoller`, then call `$poller->fetchFinalSessionStatus($session_id)`. This will return an instance of `SessionStatus`, from which you can extract the signature and certificate. Unfortunately it is still a blocking call, the method to check status only once is private, but it's better than nothing. Although in principle one could also create an instance of `SessionStatusRequest` and call `$connector->getSessionStatus($request)`, then process the result to see if the auth session has completed.

Either way, create instances of `SmartIdAuthenticationResponse` (setting necessary properties) and `AuthenticationResponseValidator`, and call `$validator->validate($response)`. This will return the final result, an instance of `SmartIdAuthenticationResult`, with `isValid()`, `getErrors()` and `getAuthenticationIdentity()` methods.

This way, depending on how much code one feels like duplicating, either the first or both of the drawbacks mentioned can be solved.
